### ISSUE TITLE
Anton Tsingel google calendar

### ISSUE THREAD

**Issue by arsenykonohovwork** [inspecta-danger-zone/idz-Membership#11]
### AC/DOD:
- [x] Create Google Calendar;
- [x] Specify Allocation;
- [x] Keep Updated;
- [x] Share with the team (chat announcement);
- [x] Attach to the wiki page for current repo;
- [x] Attach to the bottom of this description;

**Comment by AntonTsingel** [comment]
[Calendar Anton Tsingel](https://calendar.google.com/calendar?cid=dHNpbmdlbC5hbnRvbkBnbWFpbC5jb20)
