### ISSUE TITLE
Anastasiya Marshyna google calendar

### ISSUE THREAD

**Issue by arsenykonohovwork** [inspecta-danger-zone/idz-Membership#14]
### AC/DOD:
- [x] Create Google Calendar;
- [x] Specify Allocation;
- [x] Keep Updated;
- [x] Share with the team;
- [x] Attach to the wiki page for current repo;
- [x] Attach to the bottom of this description;

Done: https://calendar.google.com/calendar?cid=bWFyc2h5bmEuYW5hc3Rhc2l5YUBnbWFpbC5jb20

**Comment by marshnyash** [comment]
Done: https://calendar.google.com/calendar?cid=bWFyc2h5bmEuYW5hc3Rhc2l5YUBnbWFpbC5jb20
