### ISSUE TITLE
Rostislav Radionov google calendar

### ISSUE THREAD

**Issue by arsenykonohovwork** [inspecta-danger-zone/idz-Membership#15]
### AC/DOD:
- [x] Create Google Calendar;
- [x] Specify Allocation;
- [x] Keep Updated;
- [x] Share with the team (chat announcement);
- [x] Attach to the wiki page for current repo;
- [x] Attach to the bottom of this description;

**Comment by radionov018** [comment]
[Calendar](https://calendar.google.com/calendar/r?cid=cm9zdGlzbGF2LnJhZGlvbm92MDE4QGdtYWlsLmNvbQ&pli=1)
