### ISSUE TITLE
Anastasiya Marshyna wiki page

### ISSUE THREAD

**Issue by arsenykonohovwork** [inspecta-danger-zone/idz-Membership#7]
### AC/DOD:
- [x] visible page with description of the person as wiki page of this repo. Follow: 
- wiki tab of this repo;
- Create new Page;
- Name this page by your personal name as "Firstname Lastname";
- Update page with following data (see below);
- Create reference (link) to your page from home;
- Make sure link is working fine;
- [x] locate public info about person;
- [x] At least 2 resources should be represented right there: htmlacademy & linkedin;
- [x] Attach link to this document right here in this description as soon as you will create MVP;

Done: https://github.com/inspecta-danger-zone/idz-Membership/wiki/Anastasiya-Marshyna

**Comment by marshnyash** [comment]
Done: https://github.com/inspecta-danger-zone/idz-Membership/wiki/Anastasiya-Marshyna
